# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: FOSSA scanning

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # v4.2.2

      - uses: fossas/fossa-action@c0a7d013f84c8ee5e910593186598625513cc1e4  # v1.6.0
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          team: OpenTelemetry
